name: gbikudus_notification
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  equatable: ^2.0.7
  fpdart: ^1.1.1
  freezed_annotation: ^2.4.4
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  hive_ce: ^2.11.0
  http: ^1.2.2
  json_annotation: ^4.9.0
  shelf_cors_headers: ^0.1.5

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^2.5.7
  hive_ce_generator: ^1.9.0
  json_serializable: ^6.9.0
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
